INPUT_FILENAME:
  Charges: Data/Charges_use.csv
  Damages: Data/Damages_use.csv
  Endorse: Data/Endorse_use.csv
  Primary_Person: Data/Primary_Person_use.csv
  Units: Data/Units_use.csv
  Restrict: Data/Restrict_use.csv

OUTPUT_PATH:
  1: ./Analysis_output/TestCaseOutput_1
  2: ./Analysis_output/TestCaseOutput_2
  3: ./Analysis_output/TestCaseOutput_3
  4: ./Analysis_output/TestCaseOutput_4
  5: ./Analysis_output/TestCaseOutput_5
  6: ./Analysis_output/TestCaseOutput_6
  7: ./Analysis_output/TestCaseOutput_7
  8: ./Analysis_output/TestCaseOutput_8
  9: ./Analysis_output/TestCaseOutput_9
  10: ./Analysis_output/TestCaseOutput_10


FILE_FORMAT:
  Output: csv
